Add placement
rgeoghegan/tabulate pull request #2
Opened 2022-01-18 12:35 UTC by perleino

2022-01-18 18:19 UTC, rgeoghegan requested changes
Also, could you add a small unit test in `test_tabulate.go`. Just to show how the code should work.

2022-01-18 18:19 UTC, rgeoghegan commented on utils.go
> +func CombineHorizontal(left string, right string, padding string) string {
I would just put the `CombineHorizontal` and `CombineVertical` functions in tabulate.go, since they are meant to be part of the public interface.

2022-01-18 18:19 UTC, rgeoghegan commented on utils.go
> +func CombineHorizontal(left string, right string, padding string) string {
Also, why can I set the padding for `CombineHorizontal` but not for `CombineVertical`?

2022-01-18 18:19 UTC, rgeoghegan commented on utils.go
> +func CombineVertical(top string, bottom string) string {
Can you add an inline function doc for what the public functions do? Like in `tabulate.go` so the functions are documented like for https://pkg.go.dev/github.com/rgeoghegan/tabulate#Tabulate

2022-01-18 18:19 UTC, rgeoghegan commented on utils.go
> +		if i < len(leftSplit) && utf8.RuneCountInString(leftSplit[i]) == utf8.RuneCountInString(leftSplit[0]) {
Why not use `fmt.Fprintf` instead of sizing the strings yourself? Like

```
left := leftSplit[i]
right := rightSplit[i]
fmt.Fprintf(combined, "%*s%s%*s\n", left, leftSize, padding, right, rightSize, padding)
```

Let fmt figure out the sizing, etc.

2022-01-18 18:21 UTC, rgeoghegan commented
Looks good, if you can resolve the questions in my review, I will merge it.

2022-01-19 11:49 UTC, perleino commented on utils.go
> +func CombineHorizontal(left string, right string, padding string) string {
yeah it was more tricky to add vertical, but that should be solved now

2022-01-19 11:51 UTC, perleino commented on utils.go
> +		if i < len(leftSplit) && utf8.RuneCountInString(leftSplit[i]) == utf8.RuneCountInString(leftSplit[0]) {
i think i will leave you with this improvement, feels tricky for me to fit it in

2022-01-19 11:51 UTC, perleino commented on utils.go
> +func CombineVertical(top string, bottom string) string {
yep. i added some doc. Hope it looks good

2022-01-20 20:02 UTC, merged